#!/bin/sh
# Hack to parse the string that CMake will produce for the linker
# assumes the string contains a .o file which was generated by the compiler
# and "-o file" which would be the output of the linker.
# Since we generated only the preprocessor output we can now work with that file
# to produce our formatted cpp file.

for var in "$@"
do
    if  [[ $next_var_is_output = true ]];
    then
        output_file=$var
    fi
    if  [[ $var == *.o ]];
    then
        object_file=$var
    fi
    if  [[ $var == "-o" ]];
    then
        next_var_is_output=true
    else
        next_var_is_output=false
    fi
done

# remove all lines which have a "#"
sed -i "/^#/d" $object_file

# test if clang-format is available
clang_format_cmd="cat" # if not available use cat to pass through
command -v clang-format >/dev/null 2>&1 && clang_format_cmd="clang-format"

# removes everything before "class my_repository" and applies clang-format if available
awk "/class my_repository/,0" $object_file | eval ${clang_format_cmd} > $output_file
