image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-vscode.cmake-tools
    - llvm-vs-code-extensions.vscode-clangd

tasks:
  - init: |
      mkdir .vscode
      ln $(pwd)/.gitpod/.vscode/settings.json $(pwd)/.vscode
      ln $(pwd)/.gitpod/.vscode/launch.json $(pwd)/.vscode
      ln $(pwd)/.gitpod/CMakeUserPresets.json $(pwd)
      mkdir build
      cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --preset default -H/workspace/gridtools \
      -DCMAKE_BUILD_TYPE:STRING=Debug
      ln -s /workspace/gridtools/build/compile_commands.json .
      cmake --build /workspace/gridtools/build/ --parallel 8

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
    addLabel: false
