image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - twxs.cmake@0.0.17:9s7m9CWOr6i6NZ7CNNF4kw==
    - ms-vscode.cmake-tools@1.3.1:Yde58UUl5J9XpLmXM+Bqiw==
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
    - eamodio.gitlens@10.2.1:ZI2Sl3DHdJu4aG2wW92CQQ==

tasks:
  - init: |
      mkdir .theia && ln $(pwd)/.gitpod/.theia/settings.json .theia &&  ln $(pwd)/.gitpod/.theia/launch.json .theia
      mkdir .vscode && ln $(pwd)/.gitpod/.vscode/cmake-kits.json .vscode
      mkdir build
      cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -H/workspace/gridtools -B/workspace/gridtools/build -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles"
      ln -s /workspace/gridtools/build/compile_commands.json .
    prebuild: |
      cmake --build /workspace/gridtools/build/ --parallel 8

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
