image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - twxs.cmake@0.0.17:9s7m9CWOr6i6NZ7CNNF4kw==
    - ms-vscode.cmake-tools@1.3.1:Yde58UUl5J9XpLmXM+Bqiw==
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==

tasks:
  - init: |
      mkdir .theia && ln $(pwd)/.gitpod/.theia/settings.json .theia &&  ln $(pwd)/.gitpod/.theia/launch.json .theia
      mkdir .vscode && ln $(pwd)/.gitpod/.vscode/cmake-kits.json .vscode
      mkdir build
      cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -H/workspace/gridtools -B/workspace/gridtools/build
      ln -s /workspace/gridtools/build/compile_commands.json .
