language: minimal

services: 
  - docker

env:
  # GCC 9
  - build_type=debug float_type=float grid_type=structured compiler=gcc-9
  - build_type=release float_type=float grid_type=structured compiler=gcc-9
  - build_type=debug float_type=double grid_type=structured compiler=gcc-9
  - build_type=release float_type=double grid_type=structured compiler=gcc-9
  - build_type=debug float_type=float grid_type=icosahedral compiler=gcc-9
  - build_type=release float_type=float grid_type=icosahedral compiler=gcc-9
  - build_type=debug float_type=double grid_type=icosahedral compiler=gcc-9
  - build_type=release float_type=double grid_type=icosahedral compiler=gcc-9
  # Clang 8
  - build_type=debug float_type=float grid_type=structured compiler=clang-8
  - build_type=release float_type=float grid_type=structured compiler=clang-8
  - build_type=debug float_type=double grid_type=structured compiler=clang-8
  - build_type=release float_type=double grid_type=structured compiler=clang-8
  - build_type=debug float_type=float grid_type=icosahedral compiler=clang-8
  - build_type=release float_type=float grid_type=icosahedral compiler=clang-8
  - build_type=debug float_type=double grid_type=icosahedral compiler=clang-8
  - build_type=release float_type=double grid_type=icosahedral compiler=clang-8
  # CUDA 10.1
  # - build_type=debug float_type=float grid_type=structured compiler=cuda-10.1
  # - build_type=release float_type=float grid_type=structured compiler=cuda-10.1
  # - build_type=debug float_type=double grid_type=structured compiler=cuda-10.1
  # - build_type=release float_type=double grid_type=structured compiler=cuda-10.1
  # - build_type=debug float_type=float grid_type=icosahedral compiler=cuda-10.1
  # - build_type=release float_type=float grid_type=icosahedral compiler=cuda-10.1
  # - build_type=debug float_type=double grid_type=icosahedral compiler=cuda-10.1
  # - build_type=release float_type=double grid_type=icosahedral compiler=cuda-10.1

before_install:
  - docker pull fthaler/gridtools:test-$compiler

script:
  - docker run -v $TRAVIS_BUILD_DIR:/gridtools -e build_type=$build_type -e float_type=$float_type -e grid_type=$grid_type fthaler/gridtools:test-$compiler