#!/bin/bash
fatto=true
ID=$1
if [ -z $2 ]; then
    DURATION=3600
else
    DURATION=$2
fi
TIME=$[ `date +%s` + $DURATION ]

DONE="JobState=COMPLETED"
FAIL="JobState=FAILED"
TOUT="JobState=TIMEOUT"
while $fatto ; do
    STR1=`scontrol show jobs $ID -o -Q|gawk '{match($0, /JobState[^ ]*/); print RSTART " " RLENGHT " " substr($0, RSTART, RLENGTH);}'`
    STR=`echo $STR1 | gawk '{print $NF}'`
    if [ -n "$STR" ]; then
        printf "%s          \r" $STR ;

        if [ $STR == $DONE ]; then
            echo
            fatto=false;
            error=false
        elif [ $STR == $FAIL ]; then
            echo 
            fatto=false
            error=true
        elif [ $STR == $TOUT ]; then
            echo 
            fatto=false
            error=true
        else
            sleep 1
        fi
    else
        echo
        echo no job found or job finished
        exit 1
    fi
    if [ $TIME -lt `date +%s` ]; then
        echo Timeout while monitoring job
        exit 2
    fi
done

if [ $error ]; then
    exit 33;
else
    exit 0
fi
