#!/bin/bash
fatto=true
ID=$1
if [ -z $2 ]; then
    DURATION=3600
else
    DURATION=$2
fi
TIME=$[ `date +%s` + $DURATION ]

DONE="JobState=COMPLETED"
FAIL="JobState=FAILED"
while $fatto ; do
    JOB_IDS=`scontrol show jobs -o -Q|sed 's/JobId=\([0-9][0-9][0-9][0-9][0-9]\).*/\1/'`
    JOB_PRESENT=`for match_id in $JOB_IDS; do if [ "$match_id" -eq "$ID" ]; then echo "$ID"; fi; done`
    if ["x$JOB_PRESENT" -ne "x$ID"] # check that the job ID is still there
        exit 0
    fi
    STR1=`scontrol show jobs $ID -o -Q|gawk '{match($0, /JobState[^ ]*/); print RSTART " " RLENGHT " " substr($0, RSTART, RLENGTH);}'`
    STR=`echo $STR1 | gawk '{print $NF}'`
    if [ -n "$STR" ]; then
        printf "%s          \r" $STR ;

        if [ $STR == $DONE ]; then
            echo
            fatto=false;
        elif [ $STR == $FAIL ]; then
            echo
            fatto=false
        else
            sleep 1
        fi
    else
        echo
        echo no job found or job finished
        exit 1
    fi
    if [ $TIME -lt `date +%s` ]; then
        echo Timeout while monitoring job
        exit 2
    fi
done
