#!/bin/bash
fatto=true
ID=$1
if [ -z $2 ]; then
    DURATION=3600
else
    DURATION=$2
fi
TIME=$[ `date +%s` + $DURATION ]

DONE="JobState=COMPLETED"
FAIL="JobState=FAILED"
while $fatto ; do
    STR1=`scontrol show jobs $ID -o -Q|gawk '{match($0, /JobState[^ ]*/); print RSTART " " RLENGHT " " substr($0, RSTART, RLENGTH);}'`
    STR=`echo $STR1 | gawk '{print $NF}'`
    echo "STR1:$STR1";
    echo "STR:$STR";
    if [ -n "$STR" ]; then
        printf "%s          \r" $STR ;

        if [ $STR == $DONE ]; then
            echo
            fatto=false;
        elif [ $STR == $FAIL ]; then
            echo
            fatto=false
        else
            sleep 1
        fi
    else
        echo
        echo no job found or job finished
        exit 1
    fi
    if [ $TIME -lt `date +%s` ]; then
        echo Timeout while monitoring job
        exit 2
    fi
    JOB_IDS=`scontrol show jobs -o -Q|sed 's/JobId=\([0-9]*[0-9]\).*/\1/'`
    JOB_PRESENT=`for match_id in $JOB_IDS; do if [ "$match_id" -eq "$ID" ]; then echo "$ID" ; fi ; done`
    echo "x$JOB_PRESENT != x$ID"
    if [ "x$JOB_PRESENT" != "x$ID" ] ; then # check that the job ID is still there, otherwise exit
        echo "no job with ID $ID"
        fatto=false;
    fi
    if [ "x$STR" == "x" ] ; then # check that STR contains some value
        echo "wierd error"
        fatto=false;
    fi
done
