#!/bin/bash
PYTHON_SITE_PACKAGES=$1
CMAKE_SOURCE_DIR=$2
PYTHON_EXECUTABLE=$3
PYTHON_INSTALL_PREFIX=$4
echo "building python bindings";
export PYTHONPATH=${PYTHON_SITE_PACKAGES};
export GRIDTOOLS_ROOT=${CMAKE_SOURCE_DIR};
cd ${CMAKE_SOURCE_DIR}/python; ${PYTHON_EXECUTABLE} ${CMAKE_SOURCE_DIR}/python/setup.py build;
${PYTHON_EXECUTABLE} ${CMAKE_SOURCE_DIR}/python/setup.py install --prefix="${PYTHON_INSTALL_PREFIX}";
