cmake_minimum_required(VERSION 2.8)

option( SUPPRESS_MESSAGES "suppress compilation messages" ON)
option( VERBOSE "set verbosity for output" OFF)
set( BOOST_FUSION_MAX_SIZE 20 CACHE STRING "max sizes of boost fusion containers" )
set( ENABLE_PERFORMANCE_METERS "OFF" CACHE BOOL "If on, meters will be reported for each stencil")
option( ENABLE_PYUTILS "If on, Python utility scripts will be configured" OFF)
option( ENABLE_CUDA "Compile CUDA GPU backend examples and unit tests" OFF)
option( ENABLE_HOST "Compile CPU backend examples and unit tests" ON )
option( ENABLE_MIC "Compile MIC backend examples and unit tests" OFF )
option( COMPILE_TO_PTX "Compile to intermediate representation" OFF )
option( SINGLE_PRECISION "Option determining number of bytes used to represent the floating poit types (see defs.hpp for configuration)" OFF )
option( STRUCTURED_GRIDS "compile for rectangular grids" ON )
option( USE_MPI "Compile with MPI support" OFF )
set( GCL_MPI "${USE_MPI}" )
set( GCL_GPU "${ENABLE_CUDA}" )
option( GCL_ONLY "If on only library is build but not the examples and tests" OFF )
set( HOST_SPECIFIC_OPTIONS "" CACHE STRING "Options passed only to HOST COMPILER and not ACCELERATOR COMPILER" )
set( TEST_SCRIPT ${CMAKE_BINARY_DIR}/run_tests.sh )
set( TEST_MPI_SCRIPT ${CMAKE_BINARY_DIR}/run_mpi_tests.sh )
set( TEST_CUDA_MPI_SCRIPT ${CMAKE_BINARY_DIR}/run_cuda_mpi_tests.sh )
option( ENABLE_CACHING "Enable caching functionality" ON)
set( NVCC_CLANG_SPECIFIC_OPTIONS "" CACHE STRING "Options passed to NVCC when compiling with clang as host compiler" )
option( WERROR "Treat warnings as errors" OFF )
set( CXX_STANDARD "c++11" CACHE STRING "C++ standard to be used for compilation" )
set_property(CACHE CXX_STANDARD PROPERTY STRINGS "c++11;c++14")
option( DISABLE_TESTING "Disables all unit tests/examples" OFF )
option( COMPILE_EXAMPLES "Compiles the codes in examples folder" ON )
option( DISABLE_MPI_TESTS_ON_TARGET "Disables all the cpu communication tests" OFF )
set_property(CACHE DISABLE_MPI_TESTS_ON_TARGET PROPERTY STRINGS OFF CPU GPU)
option( ENABLE_EXPERIMENTAL_REPOSITORY "Enables downloading the gridtools_experimental repository" OFF )
option( INSTALL_GT_EXAMPLES "Specify if source codes and binaries of examples should be installed somewhere" OFF )
set( INSTALL_GT_EXAMPLES_PATH "${CMAKE_INSTALL_PREFIX}" CACHE STRING "Specify where the source codes and binaries of examples should be installed" )
