/**
 * This code was automatically generated by gridtools4py:
 * the Python interface to the Gridtools library
 *
 */
#pragma once

#include <gridtools.hpp>



using gridtools::accessor;
using gridtools::extent;

using namespace gridtools;



//
// definition of the special regions in the vertical (k) direction
//
{% for stg in stages -%}
{% for vr in stg.vertical_regions -%}
typedef gridtools::interval<level<{{ splitters[vr.start_splitter] }},-1>, level<{{ splitters[vr.end_splitter] }},-2> > {{ vr.name }};
{% endfor -%}
{% endfor -%}
typedef gridtools::interval<level<0,-2>, level<{{ splitters|length-1 }},1> > axis;

//
// the definition of the operators that compose a multistage stencil
// is extracted from the AST analysis of the loop comprehensions
// in Python, which use the 'kernel' function as a starting point
//
{{ stage_src }}
