name: CMake-config

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang:
    runs-on: ubuntu-latest
    container: mrtravis/gridtools:clang-${{ matrix.version }}
    strategy:
        matrix:
            version: [7, 8, 9]
            cuda-mode: [AUTO, Clang-CUDA, NVCC-CUDA]
    steps:
    - uses: actions/checkout@v2
    - name: CMake configure expect success
      if: contains(matrix.cuda-mode, 'AUTO')
      run: >
        mkdir build && cd build
        && cmake .. -DGT_CLANG_CUDA_MODE=${{ matrix.cuda-mode }} > out.log
        && cat out.log
        && grep "GPU mode: NOTFOUND" out.log > /dev/null
    - name: CMake configure expect failure
      if: (!contains(matrix.cuda-mode, 'AUTO'))
      run: |
        mkdir build && cd build
        if cmake .. -DGT_CLANG_CUDA_MODE=${{ matrix.cuda-mode }}; then
            false
        else
            true
        fi

  clang-cuda:
    runs-on: ubuntu-latest
    container: mrtravis/gridtools:clang-${{ matrix.version }}-cuda-10.1
    strategy:
        matrix:
            version: [9]
            # TODO re-enable NVCC-CUDA: nvcc 10.1 doesn't support clang 9
            # this never worked, but we were actually using gcc as host compiler before
            cuda-mode: [AUTO, Clang-CUDA] #, NVCC-CUDA]
    steps:
    - uses: actions/checkout@v2
    - name: CMake configure expect success
      run: >
        mkdir build && cd build
        && cmake .. -DGT_CLANG_CUDA_MODE=${{ matrix.cuda-mode }} > out.log
        && cat out.log
        && export expected_mode=${{ matrix.cuda-mode }}
        && if [ "$expected_mode" = "AUTO" ]; then export expected_mode="Clang-CUDA"; fi
        && grep "GPU mode: $expected_mode" out.log > /dev/null

  gcc:
    runs-on: ubuntu-latest
    container: mrtravis/gridtools:gcc-${{ matrix.version }}
    strategy:
        matrix:
            version: [7, 8, 9]
    steps:
    - uses: actions/checkout@v2
    - name: CMake configure expect success
      if: contains(matrix.cuda-mode, 'AUTO')
      run: >
        mkdir build && cd build
        && cmake .. > out.log
        && cat out.log
        && grep "GPU mode: NOTFOUND" out.log > /dev/null

  gcc-nvcc:
    runs-on: ubuntu-latest
    container: mrtravis/gridtools:cuda-11.0
    steps:
    - uses: actions/checkout@v2
    - name: CMake configure expect success
      run: >
        mkdir build && cd build
        && cmake .. > out.log
        && cat out.log
        && grep "GPU mode: NVCC-CUDA" out.log > /dev/null
