name: CMake

on:
  push:
    branches: [ cmake_refactoring, gh-action-cmake-checks ] #TODO point to master
  pull_request:
    branches: [ cmake_refactoring ]

jobs:
  clang:
    runs-on: ubuntu-latest
    container: mrtravis/gridtools:clang-${{ matrix.version }}
    strategy:
        matrix:
            version: [7, 8, 9]
            cuda-mode: [AUTO, Clang-CUDA, NVCC-CUDA]

    steps:
    - uses: actions/checkout@v2
    - name: CMake configure
      run: |
        mkdir build && cd build
        cmake .. -DGT_CLANG_CUDA_MODE=${{ matrix.cuda-mode }}
    - name: validate
      if: (matrix.cuda-mode == "AUTO" && success()) || failure()
      run: echo done
    #TODO parse CMake output and check if targets are available
